version: '3.4'

services:
  web:
    build:
      context: samara_renovation_of_apartaments/
      network: host
    ports:
      - "8000:8000"
    volumes:
      - ./samara_renovation_of_apartaments/:/code
    command:
      sh -c "python3 manage.py migrate && 
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./samara_renovation_of_apartaments/samara_renovation_of_apartaments/.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12-alpine
    env_file:
      - ./samara_renovation_of_apartaments/samara_renovation_of_apartaments/.env.dev