# Generated by Django 4.1.2 on 2022-10-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageTextsModel',
            new_name='HomePageSettingsModel',
        ),
    ]
