# Generated by Django 4.1.2 on 2022-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_homepagetextsmodel_homepagesettingsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesettingsmodel',
            old_name='title',
            new_name='bigest_title_text',
        ),
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='blue_navbar_button',
            field=models.CharField(default='Позвоните мне', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='tab_title',
            field=models.CharField(default='какой-то сайт', max_length=100),
            preserve_default=False,
        ),
    ]
