# Generated by Django 4.1.2 on 2022-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_homepagesettingsmodel_bigest_title_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(height_field=2325, upload_to='', width_field=3500)),
            ],
        ),
    ]
