# Generated by Django 4.1.2 on 2022-10-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projectsmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsModels',
            new_name='ProjectsModel',
        ),
    ]
