# Generated by Django 4.1.2 on 2022-10-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_projectsmodels_projectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='preview_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
