# Generated by Django 4.1.2 on 2022-10-21 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_projectsmodel_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='discount_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
