# Generated by Django 4.1.2 on 2022-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepagesettingsmodel_under_bigest_title_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
