# Generated by Django 4.1.2 on 2022-10-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactModel',
        ),
    ]
