# Generated by Django 4.1.2 on 2022-10-22 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_projectsmodel_projectmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='blue_navbar_button_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='link_to_full_reviews_list',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
