# Generated by Django 4.1.2 on 2022-10-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepagesettingsmodel_blue_navbar_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='brand_name',
            field=models.CharField(default='rem.ru', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='contacts_columns_number',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
        ),
    ]
