# Generated by Django 4.1.2 on 2022-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepagesettingsmodel_projects_columns_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettingsmodel',
            name='bigest_title_text_font_size_in_pixels',
            field=models.CharField(default='40px', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagesettingsmodel',
            name='bigest_title_text',
            field=models.TextField(max_length=100),
        ),
    ]
