# Generated by Django 4.1.2 on 2022-10-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepagesettingsmodel_bigest_title_text_font_size_in_pixels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettingsmodel',
            name='blue_navbar_button_link',
            field=models.CharField(max_length=200),
        ),
    ]
