# Generated by Django 4.1.2 on 2022-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepagesettingsmodel_blue_navbar_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_argument', models.TextField(max_length=200)),
                ('second_argument', models.TextField(max_length=200)),
                ('third_argument', models.TextField(max_length=200)),
            ],
        ),
    ]
