# Generated by Django 4.1.2 on 2022-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_add_default_seomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='alt_attribute',
            field=models.CharField(default='описание картинки с проектом', max_length=200),
            preserve_default=False,
        ),
    ]
